Import install plans
newrelic/newrelic-observability-packs pull request #225
Opened 2021-09-13 11:22 UTC by polfliet

Based on [this list of installPlans](https://docs.google.com/spreadsheets/d/1qlQoXwRd7fXffIGswZxa6dQWNuzuGvF9682ArFniizQ/edit#gid=171035041) I created a script to import them to the quickstarts.

This upgrades many documentation packs that can actually reference an existing installPlan. For example like all of the quickstarts that are related to the Java APM agent, they will now reference the installPlan for the Java agent

2021-09-13 11:23 UTC, polfliet commented
@jbeveland27 would love your review on this since you have been working on this

2021-09-13 16:52 UTC, jpvajda commented
since this PR came in from a fork, the add PR support labels and Generate UUIDs checks are failing, that's a known problem we are looking into, but this PR should be ok to merge once @jbeveland27 has time to 👍  it up.

2021-09-14 15:16 UTC, jbeveland27 commented on packs/datastax-cassandra/config.yml
> +  - cassandra-integration
This quickstart has a few things incorrect:

- It's not an on host integration
- It should be nested under the `java` quickstart
- The config needs to be reworked a bit to reflect that it's an APM agent install (fix `keywords`, etc.)

```suggestion
installPlans:
  - setup-java-agent
```

2021-09-14 15:19 UTC, jbeveland27 commented on packs/java/jayrock/config.yml
> +  - setup-java-agent
```suggestion
installPlans:
  - dotnet-agent
```

2021-09-14 15:19 UTC, jbeveland27 commented on packs/java/jayrock/config.yml
> +  - dotnet-agent
this pack should be moved to the `dotnet` folder

2021-09-14 15:21 UTC, jbeveland27 commented on packs/perfmon/config.yml
> +  - guided-install
This is an integration that's not supported by guided install
```suggestion
```

2021-09-14 15:22 UTC, jbeveland27 commented on packs/unix/config.yml
> +  - guided-install
This is an integration that's not supported by guided install
```suggestion
```

2021-09-14 15:23 UTC, jbeveland27 requested changes
Left some feedback.

2021-09-14 15:31 UTC, jbeveland27 commented
Made a few adjustments to fix install plans that had easy changes. There are a few packs that need addressed in an additional PR:

* `datastax-cassandra` - this pack should be moved under the java agent. It's not a standalone on-host integration
* `golang/go-insights` - this pack should probably just be removed, it's not the Golang agent, it's a separate module written 
* by the DTK team and it's been deprecated
* `java/grpc` - grpc is more than just the Java Agent, we should rework this pack to be more accurate
* `java/jayrock` - this is a dotnet pack, not a java pack. Should move under the `dotnet` directory
* `mysql` - this has reference to MariaDB in the name, but there's a standalone mariadb pack. Should fix the name
* php/sqlite - seems odd that this is our only sqlite reference. Should SQLite be its own pack?

----

These packs should be removed IMO. These really just point to the python agent docs, but it doesn't feel accurate to say we're doing anything special to monitor these. Our docs just link to these project sites (and some are 404s).
* python/dropbox
* python/pywapi
* python/urllib
* python/urllib2
* python/urllib3

![image](https://user-images.githubusercontent.com/6722433/133287400-f9c16f46-b9e9-4aa7-9e35-e1e3e406b4e6.png)

2021-09-14 15:32 UTC, jbeveland27 approved these changes

2021-09-14 15:34 UTC, merged

2021-09-14 15:53 UTC, jbeveland27 commented
#231 addresses all but: 

* `java/grpc` - grpc is more than just the Java Agent, we should rework this pack to be more accurate
* `php/sqlite` - seems odd that this is our only sqlite reference. Should SQLite be its own pack?