Trend Micro Cloud One - Conformity: chore
newrelic/newrelic-observability-packs pull request #236
Opened 2021-09-14 23:07 UTC by rohitkaul83

## Summary

add description for documentation, add keywords, shorten title

2021-09-14 23:45 UTC, jpvajda requested changes
I removed some keywords that aren't approved.

2021-09-14 23:45 UTC, jpvajda commented on packs/trendmicro-cloudone-conformity/config.yml
> +  - trend micro
```suggestion

```

2021-09-14 23:45 UTC, jpvajda commented on packs/trendmicro-cloudone-conformity/config.yml
> +  - cloud
```suggestion

```

2021-09-15 00:09 UTC, jpvajda commented
most of the checks are failing on this PR so we'll have to see what is occurring here. @aswanson-nr

2021-09-15 15:00 UTC, aswanson-nr commented on packs/trendmicro-cloudone-conformity/config.yml
> +    description: description: Learn more about the integration on Trend Micro's blog post
The extra `description:` here is invalidating the yaml when the CI checks attempt to read it. 
```suggestion
    description: Learn more about the integration on Trend Micro's blog post
```

2021-09-16 22:42 UTC, jpvajda commented on packs/trendmicro-cloudone-conformity/config.yml
> +  - trend micro
I'm going to let this one be used, as we are establishing a pattern where a company name could make a good keyword in other packs.

2021-09-16 22:42 UTC, jpvajda approved these changes

2021-09-16 22:42 UTC, merged