chore: Node.js Quickstart Description and Summary
newrelic/newrelic-observability-packs pull request #243
Opened 2021-09-15 17:32 UTC by aliandersonsn

Search Nurture's PR for Node.js Quickstart

## Summary

A concise description of the changes being introduced.
If this is a new Observability Pack, please provide a description of its use cases and a list of the Pack's components.

### Screenshots

Images of any visual changes, such as a dashboard.

2021-09-15 17:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-observability-packs?pullRequest=243) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-observability-packs?pullRequest=243) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-observability-packs?pullRequest=243) it.</sub>

2021-09-15 18:32 UTC, bradleycamacho commented
@jpvajda I'm taking a look at this from a language/description perspective. Can you take a look to ensure everything else looks solid? I see some checks failing.

2021-09-15 19:00 UTC, polfliet requested changes
@aliandersonsn Great to see the first PR!!

2021-09-15 21:04 UTC, jpvajda commented
Both checks are failing due to this being a fork PR, we are resolving that now, so you can just ignore it.

2021-09-15 21:06 UTC, jpvajda commented on packs/node-js/node-js/config.yml
> +  - Multiple high-value alerts, including adpex score and CPU utilization
it's apdex I assume...so i made a suggested edit.

2021-09-16 20:31 UTC, bradleycamacho commented on packs/node-js/node-js/config.yml
> +  - Multiple high-value alerts, including adpex score and CPU utilization
Fixed and capitalized

2021-09-16 20:31 UTC, bradleycamacho approved these changes
I made final copy edits. This is good to go from a content perspective!

2021-09-16 22:48 UTC, jpvajda requested changes

2021-09-16 22:48 UTC, jpvajda commented on packs/node-js/node-js/config.yml
> +  Node.js is an open-source platform built on Chrome's JavaScript runtime used to develop fast and scalable applications quickly with an event-driven, non-blocking input/output architecture. It is li
do we need to explain what node is? @bradleycamacho

2021-09-21 21:15 UTC, jpvajda commented
fixed merge conflict

2021-09-22 09:18 UTC, polfliet approved these changes

2021-09-22 09:18 UTC, merged